<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Default test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.080">
    <properties></properties>

            <testcase
                name="setUpClass"
                time="0.080"
                classname="apiPW.com.api.runner.LoginRunner">

            <failure type="java.lang.NoSuchMethodError" message="&apos;void io.cucumber.core.runtime.ObjectFactoryServiceLoader.&lt;init&gt;(java.util.function.Supplier, io.cucumber.core.backend.Options)&apos;">
                <![CDATA[java.lang.NoSuchMethodError: 'void io.cucumber.core.runtime.ObjectFactoryServiceLoader.<init>(java.util.function.Supplier, io.cucumber.core.backend.Options)'
                io.cucumber.testng.TestNGCucumberRunner.<init>(TestNGCucumberRunner.java:95)io.cucumber.testng.AbstractTestNGCucumberTests.setUpClass(AbstractTestNGCucumberTests.java:23)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:568)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)java.base/java.util.ArrayList.forEach(ArrayList.java:1511)org.testng.TestRunner.privateRun(TestRunner.java:770)org.testng.TestRunner.run(TestRunner.java:591)org.testng.SuiteRunner.runTest(SuiteRunner.java:402)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)org.testng.SuiteRunner.run(SuiteRunner.java:304)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)org.testng.TestNG.runSuitesLocally(TestNG.java:1102)org.testng.TestNG.runSuites(TestNG.java:1032)org.testng.TestNG.run(TestNG.java:1000)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </failure>
    </testcase>


</testsuite>
